sudo: false

language: python

python: 3.5

env:
  matrix:
    - TOXENV=py27-django15
    - TOXENV=py27-django16
    - TOXENV=py27-django17
    - TOXENV=py27-django18
    - TOXENV=py27-django19
    - TOXENV=py27-django110
    - TOXENV=py27-django111

    - TOXENV=py33-django15
    - TOXENV=py33-django16
    - TOXENV=py33-django17
    - TOXENV=py33-django18

    - TOXENV=py34-django15
    - TOXENV=py34-django16
    - TOXENV=py34-django17
    - TOXENV=py34-django18
    - TOXENV=py34-django19
    - TOXENV=py34-django110
    - TOXENV=py34-django111

    - TOXENV=py35-django18
    - TOXENV=py35-django19
    - TOXENV=py35-django110
    - TOXENV=py35-django111


matrix:
  include:
    - python: 3.4
      env: DJANGO=1.8  COVERAGE=true  COVERALLS_REPO_TOKEN=LdECqqwg7eelQx9w8gvooUZCFIaCqGZCv

    - python: 3.4
      env: TOXENV=lint

  allow_failures:
    - env: COVERAGE=true

install:
  - pip install -U pip setuptools
  - pip install tox
  - make install

script:
  - tox

after_script:
  - if [ "$COVERAGE" == "true" ]; then
    pip install --quiet python-coveralls;
    make coverage;
    coverage report;
    coveralls --ignore-errors;
    fi

notifications:
  email:
    - hannes@5monkeys.se
